@extends("layouts.admin")
@section("title","مدیریت سفارش‌ها")
@section("page-title","مدیریت سفارش، پرداخت و ارسال")
@section("page-subtitle","کنترل چرخه سفارش از ثبت تا تحویل")
@section("content")
@php($fa=fn($n)=>\App\Support\Jalali::digits(number_format($n)))
<div class="kpi-grid four"><article class="kpi orange"><span>کل سفارش‌ها</span><strong>{{ $fa($orders->total()) }}</strong></article><article class="kpi red"><span>مطالبات باز</span><strong>{{ $fa($receivables) }} ریال</strong></article><article class="kpi green"><span>مرسوله‌های اخیر</span><strong>{{ $fa($shipments->count()) }}</strong></article><article class="kpi blue"><span>استعلام‌های پروژه</span><strong>{{ $fa($quotes->count()) }}</strong></article></div>
<section class="panel data-panel"><div class="toolbar"><h2>سفارش‌ها</h2><a class="main-action" href="{{ route("admin.orders.export") }}">خروجی CSV</a></div><div class="table-wrap"><table><thead><tr><th>کد</th><th>مشتری</th><th>مبلغ</th><th>وضعیت</th><th>پرداخت</th><th>ارسال</th><th>تاریخ</th><th>بروزرسانی</th></tr></thead><tbody>
@foreach($orders as $o)<tr><td>{{ $o->order_no }}</td><td>{{ optional($o->customer)->name ?: optional($o->user)->name ?: "مشتری" }}</td><td>{{ $fa($o->total) }} ریال</td><td>{{ $o->status }}</td><td>{{ $o->payment_status }}</td><td>{{ $o->shipping_status }}</td><td>{{ \App\Support\Jalali::date($o->ordered_at) }}</td><td><form class="row-edit" method="post" action="{{ route("admin.orders.update",$o) }}">@csrf @method("PATCH")<select name="status"><option value="processing" @selected($o->status==="processing")>در پردازش</option><option value="confirmed" @selected($o->status==="confirmed")>تایید</option><option value="completed" @selected($o->status==="completed")>تکمیل</option><option value="cancelled" @selected($o->status==="cancelled")>لغو</option></select><select name="payment_status"><option value="unpaid" @selected($o->payment_status==="unpaid")>پرداخت نشده</option><option value="pending" @selected($o->payment_status==="pending")>در انتظار</option><option value="paid" @selected($o->payment_status==="paid")>پرداخت شده</option><option value="partial" @selected($o->payment_status==="partial")>بخشی</option></select><select name="shipping_status"><option value="preparing" @selected($o->shipping_status==="preparing")>آماده‌سازی</option><option value="ready" @selected($o->shipping_status==="ready")>آماده ارسال</option><option value="in_transit" @selected($o->shipping_status==="in_transit")>در مسیر</option><option value="delivered" @selected($o->shipping_status==="delivered")>تحویل شد</option></select><button>ذخیره</button></form></td></tr>@endforeach
</tbody></table></div>{{ $orders->links() }}</section>
@endsection
